/* 
    altsquare_aux.m                                                                RecogniseSmallDim

    This file contains some auxiliary functions necessary for the recognition of exterior squares of 
    for Sp(n,q).

    Written by Csaba Schneider.
    Analysed in February 2024 and August 2024
*/

import "smalldimreps.m":funcpos_altsquare, SolveAltSquareDimEq, __funcAltSquareToSLdq, __funcSLdqToAltSquare, funcposinv_altsquare;
import "auxfunctions.m": InvolutionWithProperty, MyDerivedGroupMonteCarlo;
/* 
    This file contains some auxiliary functions that are necessary for the recognition of the exterior square 
    representations, especially in the case of the symplectic groups. 

    Suppose that M is the large irreducible factor of the exterior square of V where V is the natural module for the 
    symplectic group. Suppose that V = U + W is a decomposition of V into the direct sum of non-degenerate subspaces 
    and also assume that the characteristic p does not divide dim U and dim V. Suppose that C is the 
    stabilizer of the decomposition, and so C = Sp(U) x Sp(W).

    If the characteristic p does not devide dim V, then 

    M = H + K + T + W

    where H and K are the large irreducible quotients of Lambda^2 U and Lambda^2 W, respectively and T = U tensor W. 
    Furthermore, H + W = Lambda^2 U and K + W = Lambda^2 W.

    if p divides dim V, then 

    M = H + K + W

    where H and K are the large irreducible quotients of Lambda^2 U and Lambda^2 W, respectively and T = U tensor W.

*/


/*
    Suppose that n = d1+d2, e1,...,en are the standard row basis vectors of F^n. This function builds a matrix whise rows are 
    
    e1-ed1, e2-ed1, ...,e{d1-1}-ed1, e1+e2+...+ed1      and 
    e{d1+1}-en, e{d1+2}-edn, ...,e{n-1}-en, e{d1+1}+e{d1+2}+...+en.
    
    This is used when e1, e2, etc, represent e1f1, e2f2, ..., enfn and the natural module V is decomposed into components of dimension 
    d1 and d2.
*/


SpTransformMatrix := function( d1, d2, F )
    
    d := d1+d2;
    assert IsEven( d );
    dd1 := d1 div 2; dd2 := d2 div 2; dd := d div 2;
    
    M := ZeroMatrix( F, d div 2, d div 2 );
    
    for i in [1..dd1-1] do
        M[i,i] := 1; M[i,dd1] := -1;
    end for;
    
    for i in [1..dd1] do
        M[dd1,i] := 1;
    end for;
    
    for i in [1..dd2-1] do
        M[dd1+i,dd1+i] := 1; M[dd1+i,dd] := -1;
    end for;
    
    for i in [1..d2 div 2] do
        M[dd,(dd1 + i)] := 1;
    end for;
    
    return M;
end function; 
    
/* 
    Returns the basis of the vector space generated by the rows of the matrix in the previous function.

    If pdividesd is true, then returns the vector space generated by the 
    first d1/2 - 1 elemenets
    the elements with index d1/2+1 to d, and 
    the sum of the d1/2 and d/2 entry.
*/

SpSubspaceMatrix := function( d1, d2, F )    

    d := d1 + d2;
    pdividesd := d mod Characteristic( F ) eq 0;
    dd1 := d1 div 2; dd2 := d2 div 2; dd := d div 2;
    mat := SpTransformMatrix( d1, d2, F );
    if pdividesd then
        return Matrix( mat[1..dd1-1] cat mat[dd1+1..dd-1] cat [ mat[dd1]+mat[dd]] );
    else  
        return mat;
    end if;

end function;


BuildBasisMatrixSp := function( F, dU, dW : scalars := [1,1,1,1] )

    dim := dU + dW;
    p := Characteristic( F );
    pdividesd := dim mod p eq 0;
    dH := dU*(dU-1) div 2 - 1; dK := dW*(dW-1) div 2 - 1;
    a := scalars[1]; b := scalars[2]; c := scalars[3]; d := scalars[4]; 

    matrix_nr_rows := dim*(dim-1) div 2 - 1;
    matrix_nr_cols := dim*(dim-1) div 2 - case< pdividesd | true: 2, default: 1 >; 
    bas := ZeroMatrix( F, matrix_nr_rows, matrix_nr_cols );
    poswH := dH + dK + dU*dW + 1;
    V := VectorSpace( F, matrix_nr_cols );

    // divide dimensions by 2
    dd := dim div 2; ddU := dU div 2; ddW := dW div 2;
    
    /* 
       we think of the spaces H and K to be spaced as 
       e1,...,ed,e{d+1},...,en,fn,...,f{d+1},fd,...,f1
       where H is <e_1,...,ed,fd,...,f1>, while K is <e{d+1},...,en,fn,...,f{d+1}>
       we calculate the indices for the basis vectors that belong to H and K.
    */

    rangeH := [1..ddU] cat [ddU+dW+1..dim]; rangeK := [ddU+1..ddU+dW];

    /* 
      We generate basis of the subspace that corresponds to 
      e1f1 - edfd, ..., e{d-1}f{d-1}, 
      (*) e1f1+e2f2+...+edfd
      e{d+1}f{d+1}-enfn,...,e{n-1}f{n-1}-enfn, 
      (*) e{d+1}f{d+1}+...+enfn

      if pdividesd then the two basis elements with (*) are omitted and 
      e1f1+...+enfn is added in the last position.
    */

    subspmatrix := SpSubspaceMatrix( dU, dW, F );

    // we create the list of basis elements from basH that are of the form 
    // e1f1-edfd, ..., e{d-1}f{d-1}-edfd 
    vecs_ex := [ funcpos_altsquare( dU, i, dU-i+1 : type := "Sp" ) : i in [1..ddU-1]];
    vecs_ex_scalars := [ a : _ in [1..#vecs_ex]];
    
    // if not pdividesd then we add the generator of wH which corresponds to
    // e1f1+...+edfd 
    if not pdividesd then
        Append( ~vecs_ex, poswH );
        Append( ~vecs_ex_scalars, d );
    end if;
    
    // we add the basis elements e{d+1}f{d+1}-enfn
    vecs_ex := vecs_ex cat [ ( dH + funcpos_altsquare( dW, i, dW-i+1 : type := "Sp" )) : i in [1..ddW-1]];
    vecs_ex_scalars cat:= [ b : _ in [1..ddW-1]];
    
    // if needed we add -wH which corresponds to e{d+1}f{d+1}+...+enfn
    if not pdividesd then
        Append( ~vecs_ex, poswH );
        Append( ~vecs_ex_scalars, -d );
    end if;

    // V0 represents the vector space generated by the e1f1,...,enfn
    V0 := VectorSpace( F, dd ); ZV0 := Zero( V0 );

    // we build up the basis for V from the bases in the input
    // the indices run for 1 <= i < j <= d
    for i in [1..dim], j in [i+1..dim] do
        i0 := i; j0 := j;
        // the basis element enfn skipped
        if i0 eq dd and j0 eq dd+1  then
            continue j;
        end if;

        // the first option is when the corresponding basis element comes from H
        if i0 in rangeH and j0 in rangeH then
                
            // Since K is inserted into the middle of H, i0 and j0 has to be offset if they 
            // represent fi    
            if i0 gt ddU then i0 -:= dW; end if;
            if j0 gt ddU then j0 -:= dW; end if;

            // if the basis element <i0,j0> is not eifi-enfn    
            if i0+j0 ne dU+1 then
                pos := funcpos_altsquare( dim, i, j : type := "Sp" );
                if  pos gt Nrows( bas ) then 
                    continue;
                end if;
                bas[ pos,funcpos_altsquare( dU, i0, j0 : type := "Sp" )] := a;    
            else  
                // the vector to be treated is of the type eifi - enfn
                // we need to write it as a linear combination of the basis vectors of basH and basK
                // first we build this vector                 
                vec := ZV0; vec[i0] := 1; vec[dd] := -1;
                // compute its coeffs in the basis of subsp
                vec := Solution( subspmatrix, vec );
                vec1 := Zero( V ); 
                // take the linear combination of the elements in vecs_ex with these coefficients
                // insert into the right position
                for l in [1..#vecs_ex] do 
                    vec1[vecs_ex[l]] +:= vecs_ex_scalars[l]*vec[l];
                end for; 
                //error(111);
                bas[ funcpos_altsquare( dim, i, j : type := "Sp" )] := vec1;                    
            end if;
        
        // the next option is when i0, j0 represent a vector in K
        elif i0 in rangeK and j0 in rangeK then
                
            // we calculate the position relative to K
            i0 -:= ddU; j0 -:= ddU;


            if i0 + j0 ne dW +1 then   
                // when the vector is not of the form eifi - enfn 
                bas[ funcpos_altsquare( dim, i, j : type := "Sp" ), dH+funcpos_altsquare( dW, i0, j0 : type := "Sp" )] := b;
            else
                // type eifi - enfn handled as in the H-type vectors above                
                vec := ZV0; vec[ddU+i0] := 1; vec[dd] := -1;
                vec := Solution( subspmatrix, vec );
                vec1 := Zero( V ); 
                for l in [1..#vecs_ex] do 
                    vec1[vecs_ex[l]] +:= vecs_ex_scalars[l]*vec[l];
                end for; 
                bas[ funcpos_altsquare( dim, i, j : type := "Sp" )] := vec1;
            end if;
                
        // here we handle H x K type vectors that lie in the tensor product
        // component
        elif i0 in rangeH and j0 in rangeK then
            bas[ funcpos_altsquare( dim, i, j : type := "Sp" ),dH+dK+(i0-1)*dW+j0-ddU] := c;

        // in the case of K x H vectors, the same procedure, but multiplying with -1
        elif i0 in rangeK and j0 in rangeH then                                
            bas[ funcpos_altsquare( dim, i, j : type := "Sp" ),dH+dK+(j0-dW-1)*dW+i0-ddU] := -c;
        end if;
    end for;
    

    // if pdividesd then we remove the basis element corresponding to e{d-1}f{d-1}
    if pdividesd then
        RemoveRow( ~bas, funcpos_altsquare( dim, dd -1, dd + 2 ));
    end if;

    return bas;
end function;

/* 
   Builds standard basis for V in the case of sympectic groups acting on the exterior square. 
   We assume that V = U + W and we have standard bases for H = U wedge U, K = W wedge W, and for T = U tensor W. 
   We can also pass on optional argument scalars which specifies a scalar factors and wH which specifies  
*/

BuildBasisMatrix := function( F, dU, dW : wH := [], type := "SL" )

    if type eq "Sp" then 
        return BuildBasisMatrixSp( F, dU, dW );
    end if;

    dT := dU*dW;
    d := dU + dW;
    dimg := d*(d-1) div 2;
    dimH := dU*(dU-1) div 2;
    dimK := dW*(dW-1) div 2;
    bas_matrix := ZeroMatrix( F, dimg, dimg ); 

    for i in [1..dU], j in [i+1..dU] do
        bas_matrix[funcpos_altsquare( d, i, j ),funcpos_altsquare( dU, i, j )] := 1;
        //Vector( basH[funcpos_altsquare( dH, i, j )]);
    end for;
    
    for i in [dU+1..d], j in [i+1..d] do
        bas_matrix[funcpos_altsquare(d, i, j ),dimH+funcpos_altsquare( dW, i-dU, j-dU )] := 1;
        //Vector( basK[funcpos_altsquare( dK, i-dH, j-dH )] );
    end for;
    
    for i in [1..dU], j in [dU+1..d] do
        bas_matrix[funcpos_altsquare( d, i, j ),dimH+dimK+(i-1)*dW+j-dU] := 1;
        //Vector( tbas[(i-1)*dK+j-dH] );
    end for;

    return bas_matrix;
end function;

            

// the following functions tests if a system of bases for H, K, T, wH, and wK is the right one
// up to +-1 scalars.

// THIS FUNCTION NEEDS CHECKING! Is it enough to take one random number?

TestBasisSp := function( basH, basK, basT, wH, g )
    
    F := CoefficientRing( g );
    p := Characteristic( F );
    dimg := Dimension( g );
    dim := SolveAltSquareDimEq( dimg : type := "Sp" );
    pdividesd := dim mod p eq 0;
    dH := SolveAltSquareDimEq( #basH : type := "Sp" );
    dK := SolveAltSquareDimEq( #basK : type := "Sp" );
    

    // the possible combinations for the scalars
    scalars := [ <a,b,c,d > : a in [1,-1], b in [1,-1], c in [1,-1], 
                 d in [1,-1]]; 
    
    // check all possible combinations of scalars
    for s in scalars do 
        // build the basis
        bas := BuildBasisMatrixSp( F, dH, dK : scalars := s )*Matrix( basH cat basK cat basT cat wH );
        //BuildBasisSp( basH, basK, basT, wH : scalars := [s[1], s[2], s[3], s[4]] );
        bas_mat := Matrix( bas );
        // take random element from the group
        // we want one outside of the center
        repeat 
            x0 := Random( g );
        until (x0,Random(g)) ne x0^0;
        // apply basis transform on x0
        x := bas_mat*x0*bas_mat^-1;
        // find preimage of x
        y := __funcAltSquareToSLdq( x : type := "Sp" );
        // check if the result is valid
        if Category( y ) eq BoolElt then continue; end if;
        // find image of y and check if result is valid
        x1 := __funcSLdqToAltSquare( y : type := "Sp" );
        if Category( x1 ) eq BoolElt or not IsInvertible( x1 ) then continue; end if;
        // x should be x1 if the scalars are right
        if x eq x1  then
            return true, s;
        end if;
    end for;
    
    return false, _;
end function;
    
// a part of the basis calculated in the main function might need to be multiplied by a scalar
// this is done in this function 
find_scalar_for_mT := function( G, tr, dim, dH, q )

    p12 := funcpos_altsquare( dim, 1, 2 );
    p13 := funcpos_altsquare( dim, 1, dH+1 );
    p23 := funcpos_altsquare( dim, 2, dH+1 );
    p14 := funcpos_altsquare( dim, 1, dH+2 );
    p34 := funcpos_altsquare( dim, dH+1, dH+2 );

    repeat
        x := tr*Random( G )*tr^-1;
        mat1 := Matrix( GF( q ), 3, 3, [
                        x[p12,p12],    x[p12,p13],    x[p12,p23],
                        x[p13,p12],    x[p13,p13],    x[p13,p23],        
                        x[p23,p12],    x[p23,p13],    x[p23,p23]] );
        
        mat2 := Matrix( GF( q ), 3, 3, [
                        x[p13,p13],    x[p13,p14],    x[p13,p34],
                        x[p14,p13],    x[p14,p14],    x[p14,p34],        
                        x[p34,p13],    x[p34,p14],    x[p34,p34]] );
        
        if Determinant( mat1 ) eq 0 or Determinant( mat2 ) eq 0 then 
            mm1 := ZeroMatrix( GF( q ), 3 );
            mm1 := ZeroMatrix( GF( q ), 3 );
        else
            mm1 := __funcAltSquareToSLdq( mat1 ); 
            mm2 := __funcAltSquareToSLdq( mat2 );
        end if;
                        
    until mm1[1,1] ne 0 and mm1[1,3] ne 0;

    assert mm1[1,1] eq mm2[1,1];
    
    lambdasq := mm1[1,3]/mm2[1,2]; 
    is_sq, lambda := IsSquare( lambdasq );
    
    if is_sq then 
      for i in [1..dH], j in [dH+1..dim] do
            pij := funcpos_altsquare( dim, i, j ); tr[pij] := lambda*tr[pij];
       end for; 
    else 
      z0 := PrimitiveElement( GF( q ));
      lambda := Sqrt( z0*lambdasq );
      for i in [1..dH], j in [dH+1..dim] do
            pij := funcpos_altsquare( dim, i, j ); tr[pij] := lambda*tr[pij];
      end for;
    
      for i in [dH+1..dim], j in [i+1..dim] do
            pij := funcpos_altsquare( dim, i, j );
            tr[pij] := z0*tr[pij];
      end for;
    end if; 
    return tr;
end function;

 /* find an involution with sufficiently large minus one eigenspace and 
       its centraliser. */

InvolutionWithCentralizer := function( G, type, dimG, dim )
    
    // the eigenspace dimensions are set using heuristics
    // eiglim1: lower limit; eiglim2: upper limit for eigenspaces
    if type eq "Omega-" and dim eq 12 then 
        eiglim1 := 36; eiglim2 := 36;
    elif type eq "Omega" and dim eq 9 then 
        eiglim1 := 18; eiglim2 := 18;
    elif type eq "Sp" and dim eq 6 then 
        eiglim1 := 9; eiglim2 := 9;
    elif type eq "Sp" and dim eq 14 then 
        eiglim1 := 40; eiglim2 := 49;
    elif type eq "Sp" and dim eq 12 then 
        eiglim1 := 32; eiglim2 := 36;
    else 
        eiglim1 := case< dim | 6: 8, 11: 29, 12: 35, default: (2/9)*dim^2 >; 
        //eiglim1 := case< dim | 6: 8, 11: 29, 12: 35, default: (2/9)*dim^2 >;
        eiglim2 := case< dim | 6: 8, default: (1/4)*dim^2 >; 
    end if;
      
    // set up property function for InvolutionWithProperty  
    propfunc := function( x )
        dmin := Dimension( Eigenspace( x, -1 ));  
        return dmin ge eiglim1 and dmin le eiglim2;
    end function;
        
    // completion checking function    
    NrGensCentInv := 10; 
    __compcheck := func< G, C, g | NumberOfGenerators( C ) ge NrGensCentInv >;
    
    
    if type eq "Sp" then 
        // we want to take the perfect subgroup inside the centralizer of the 
        // involution. This variable shows how deep we need to go inside the 
        // derived series.
        dl := 3;
        // the number of components in the C0-module
        nocomponents := case< dim mod Characteristic( CoefficientRing( G )) eq 0 | true: 3, default: 4 >;
        // this function returns true if the condition we want for the dimensions of the 
        // CD-components is true
        good_dims := function( dims ) 
            
            // first we want the right number of dimensions and they should add up 
            // to dimG
            if #dims ne nocomponents or &+dims ne dimG then 
                return false;
            end if;
            // if #dims ne 3 then return true; end if;
            // we also want that the product of the dimensions of the two alt-components 
            // should be equal to the tensor component
            dims1 := [ SolveAltSquareDimEq( x : type := "Sp", pmaydividedim := false ) : x in dims ];
            poszero := [ x : x in [1..#dims] | dims1[x] eq 0 and dims[x] ne 1 ];
            posnonzero := [ x : x in [1..#dims] | dims1[x] ne 0 and dims[x] ne 1 ];
            return &*dims1[posnonzero] eq dims[poszero][1];
        end function;
    else 
        // the same when the type is not Sp
        dl := case< dim | 8: 2, 9: 2, 10: 2, 11: 2, 12: 2, 18: 2, default : 1 >;
        nocomponents := 3;
        good_dims := func< dims | #dims eq nocomponents and not 1 in dims and &+dims eq dimG >;
    end if; 

    repeat
        // get an involution with the right eigenspace dimensions   
        inv := InvolutionWithProperty( G, propfunc ); 
        // set up lists for the generators of the centralizer and its derived subgroup
        gensC := []; gensCD := [];
        
        // we need to find its centralizer. The centralizer of involution function may not 
        // return the full centralizer, and this is why we need to repeat.
        // TODO: Is it simpler to chose another involution when Cent is too small?
        
       repeat 
            // find the centralizer of inv and its derived subgroup
            C := CentraliserOfInvolution( G, inv : CompletionCheck := __compcheck );   
            CD := MyDerivedGroupMonteCarlo( C : 
                      NumberGenerators := NrGensCentInv,
                      DerivedLength := dl );      

            // add the computed generators to the ones that were computed
            gensC := gensC cat GeneratorsSequence( C );
            gensCD := gensCD cat GeneratorsSequence( CD );
            // update C and CD
            C := sub< Universe( gensC ) | gensC >;
            CD := sub< Universe( gensCD ) | gensCD >;

            // compute the CD-module and its minimal submodules
            M := GModule( CD );
            mins := [ x : x in MinimalSubmodules( M : Limit := 4 )];
            // If M contains a unique submodule of dimension 1, then it is hopless and we get another 
            // involution
            dim_mins := [ Dimension( x ) : x in mins ]; 
            nr_ones := #[ x : x in [1..#mins] | dim_mins[x] eq 1 ];
            // if M has more than 4 minimal submodules, then we need more generators
            // and so we repeat the centralizer computation
            stop_condition := #mins lt nocomponents + 1 or nr_ones eq 1;
            //print dim_mins;
        until stop_condition;  
    // the right centralizer should have 3 minimal submodules that form a direct sum            
    until  good_dims( dim_mins );

    return inv, gensCD, CD, M, mins;
end function;

/* 
   find the right basis transformation matrix

   This functions puts together the right transformation matrix from the bases of the components 
   H, K, T, and the one-dimensional component. 
*/

find_right_tr_matrix := function( G0, bas_mat, dim, dimg, dH, dK, basH, basK, basT, basOneDim )

    // set up some variables
    q := #CoefficientRing( G0 );
    _, p := IsPrimePower( q );
    pdividesd := dim mod p eq 0;
    z := PrimitiveElement( GF( q ));

    // convert G0 to the form determined by bas_mat
    g := sub< SL( dimg, q ) | { bas_mat*x*bas_mat^-1 : x in Generators( G0 )}>;
    // g preserves a bilinear form
    form := ClassicalForms( g )`bilinearForm;
    
    // here we sample the values of the form to determine the right scalars

    // calculate the entry in the Gram matrix that corresponds to 
    // <f1f{d+1},e1e{d+1}>
    posT := funcpos_altsquare( dim, dim, dim-dH div 2 : type := "Sp" );
    if pdividesd then posT -:= 1; end if;  
    value_T := form[dH div 2,posT];
    value_H := Sqrt( form[1,dimg] )^-1;
    // calculate the entry in the Gram matrix that corresponds to 
    // <e{d+1}e{d+2},f{d+1}f{d+2}>
    posK1 := funcpos_altsquare( dim, dH div 2+1, dH div 2+2 : type := "Sp" );
    posK2 := funcpos_altsquare( dim, dim-dH div 2-1, dim-dH div 2 : type := "Sp" );
    if pdividesd then posK2 -:= 1; end if; 
    value_K := Sqrt( form[posK1,posK2] )^-1;

    if not pdividesd then
       vect := (BuildBasisMatrixSp( GF( q ), dH, dK )^-1)[dimg];
       posV := funcpos_altsquare( dim, dH div 2 + 1, dim div 2 + dK div 2  : type := "Sp" );
       u := vect[dim-1]; v := vect[posV];
       assert u ne 0 and v ne 0;
       b0_st := -u^2*(dH div 2) - v^2*(dK div 2); 
       b0 := (vect*form*Transpose( Matrix( vect )))[1];
       value_Z := Sqrt( b0_st/b0 );
       basOneDim[1] *:= value_Z;
    end if; 

    // in the form that is preserved the value of <e1*e{d+1},f1*f{d+1}> must be a squaree
    if not IsSquare( value_T ) then 
        // if not square, we modify the basis of H. we simulate the multplication of 
        // the basis element e_i for i in {1...d} by the primitive element z.
        for i in [1..#basH] do 
            pos := funcposinv_altsquare( dH, i : type := "Sp" );
            // multiply things of the form ei*ej by z^2 
            if pos[1] le dH div 2 and pos[2] le dH div 2 then
                basH[i] *:= z^2;
            // multiply things of the form ei*fj by z
            elif pos[1] le dH div 2 and pos[2] gt dH div 2 then
                basH[i] *:= z;
           end if;
        end for;

        // we also multiply elements of basT by z 
        for i in [1..#basT/2] do 
            basT[i] *:= z;
        end for;
        value_H *:= z^-1;
        value_T := Sqrt( z*value_T )^-1;
    else 
        value_T := Sqrt( value_T )^-1;
    end if;    

   
   // modyfy basis elements so that the Gram matrix is contains ones
   for i in [1..#basH] do 
       basH[i] *:= value_H;
   end for;
   
   for i in [1..#basK] do
       basK[i] *:= value_K;
   end for;

       
   for i in [1..#basT] do
       basT[i] *:= value_T;
   end for;

   // determine the final coefficients
   v, coeffs := TestBasisSp( basH, basK, basT, basOneDim, G0 );  assert v; 
   return BuildBasisMatrixSp( GF(q), dH, dK : scalars := coeffs )*Matrix( basH cat basK cat basT cat basOneDim );
end function;

